### ISSUE TITLE
sort by datetime fields

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/data#93]
### What steps will reproduce the problem?

in `yii-demo` modify the following file: `src/Blog/Comment/CommentRepository.php` from:

```
    private function getSort(): Sort
    {
        return Sort::only(['id', 'public', 'created_at', 'post_id', 'user_id'])->withOrder(['id' => 'asc']);
    }
```
to:
```
    private function getSort(): Sort
    {
        return Sort::only(['id', 'public', 'created_at', 'post_id', 'user_id'])->withOrder(['created_at' => 'desc']);
    }
```
### What is the expected result?

comments are sorted descending order for `created_at` fields

### What do you get instead?

```
Yiisoft\ErrorHandler\Exception\ErrorException: Undefined property: App\Blog\Entity\Comment Cycle ORM Proxy::$created_at in /app/vendor/cycle/orm/src/Mapper/Proxy/EntityProxyTrait.php:28
Stack trace:
#0 /app/vendor/cycle/orm/src/Mapper/Proxy/EntityProxyTrait.php(28): Yiisoft\ErrorHandler\ErrorHandler::Yiisoft\ErrorHandler\{closure}(2, 'Undefined prope...', '/app/vendor/cyc...', 28)
#1 /app/vendor/yiisoft/arrays/src/ArrayHelper.php(255): App\Blog\Entity\Comment Cycle ORM Proxy->__get('created_at')
#2 /app/vendor/yiisoft/arrays/src/ArrayHelper.php(231): Yiisoft\Arrays\ArrayHelper::getRootValue(Object(App\Blog\Entity\Comment Cycle ORM Proxy), 'created_at', NULL)
#3 /app/vendor/yiisoft/data/src/Paginator/KeysetPaginator.php(316): Yiisoft\Arrays\ArrayHelper::getValue(Object(App\Blog\Entity\Comment Cycle ORM Proxy), 'created_at')
#4 /app/vendor/yiisoft/data/src/Paginator/KeysetPaginator.php(262): Yiisoft\Data\Paginator\KeysetPaginator->getValueFromItem(Object(App\Blog\Entity\Comment Cycle ORM Proxy), 'created_at')
#5 /app/vendor/yiisoft/data/src/Paginator/KeysetPaginator.php(174): Yiisoft\Data\Paginator\KeysetPaginator->readData(Object(Yiisoft\Yii\Cycle\Data\Reader\EntityReader), Object(Yiisoft\Data\Reader\Sort))
#6 /app/views/blog/comments/_comments.php(19): Yiisoft\Data\Paginator\KeysetPaginator->read()
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | master
| PHP version      |  8.1
| Operating system | Linux (yii-php docker image)

**Comment by vjik** [comment]
Seems, problem here:

https://github.com/yiisoft/data/blob/55fd80895765cae9e125489d2c119b150ac4e596/src/Paginator/KeysetPaginator.php#L309

For `post_id` method name is `getPost_id`.

May be we can remove magic here?

**Comment by samdark** [comment]
Removing magic is good. How would you do it?

**Comment by albertborsos** [comment]
Ok, that is an issue too, but after I update it to `$methodName = 'get' . (new Inflector())->tableToClass($field);` then I will get this error:

```
Error: Object of class DateTimeImmutable could not be converted to string in /app/vendor/yiisoft/data/src/Paginator/KeysetPaginator.php:264
Stack trace:
#0 /app/vendor/yiisoft/data/src/Paginator/KeysetPaginator.php(176): Yiisoft\Data\Paginator\KeysetPaginator->readData(Object(Yiisoft\Yii\Cycle\Data\Reader\EntityReader), Object(Yiisoft\Data\Reader\Sort))
#1 /app/views/blog/comments/_comments.php(19): Yiisoft\Data\Paginator\KeysetPaginator->read()
#2 /app/vendor/yiisoft/view/src/PhpTemplateRenderer.php(28): require('/app/views/blog...')
#3 /app/vendor/yiisoft/view/src/PhpTemplateRenderer.php(37): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}('/app/views/blog...', Array)
#4 /app/vendor/yiisoft/view/src/ViewTrait.php(449): Yiisoft\View\PhpTemplateRenderer->render(Object(Yiisoft\View\WebView), '/app/views/blog...', Array)
#5 /app/vendor/yiisoft/view/src/ViewTrait.php(402): Yiisoft\View\WebView->renderFile('/app/views/blog...', Array)
#6 /app/views/blog/comments/index.php(25): Yiisoft\View\WebView->render('_comments', Array)
#7 /app/vendor/yiisoft/view/src/PhpTemplateRenderer.php(28): require('/app/views/blog...')
#8 /app/vendor/yiisoft/view/src/PhpTemplateRenderer.php(37): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}('/app/views/blog...', Array)
#9 /app/vendor/yiisoft/view/src/ViewTrait.php(449): Yiisoft\View\PhpTemplateRenderer->render(Object(Yiisoft\View\WebView), '/app/views/blog...', Array)
#10 /app/vendor/yiisoft/view/src/ViewTrait.php(402): Yiisoft\View\WebView->renderFile('/app/views/blog...', Array)
#11 /app/vendor/yiisoft/yii-view/src/ViewRenderer.php(322): Yiisoft\View\WebView->render('index', Array)
#12 /app/vendor/yiisoft/yii-view/src/ViewRenderer.php(119): Yiisoft\Yii\View\ViewRenderer->renderProxy('index', Array, Array, Array, Array, Array)
#13 /app/vendor/yiisoft/data-response/src/DataResponse.php(324): Yiisoft\Yii\View\ViewRenderer->Yiisoft\Yii\View\{closure}()
#14 /app/vendor/yiisoft/data-response/src/Formatter/HtmlDataResponseFormatter.php(43): Yiisoft\DataResponse\DataResponse->getData()
#15 /app/vendor/yiisoft/data-response/src/DataResponse.php(353): Yiisoft\DataResponse\Formatter\HtmlDataResponseFormatter->format(Object(Yiisoft\DataResponse\DataResponse))
#16 /app/vendor/yiisoft/data-response/src/DataResponse.php(106): Yiisoft\DataResponse\DataResponse->formatResponse()
#17 /app/vendor/yiisoft/cookies/src/CookieMiddleware.php(148): Yiisoft\DataResponse\DataResponse->getHeader('Set-Cookie')
#18 /app/vendor/yiisoft/cookies/src/CookieMiddleware.php(85): Yiisoft\Cookies\CookieMiddleware->encodeResponseSetCookieHeaders(Object(Yiisoft\DataResponse\DataResponse))
#19 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(104): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#20 /app/vendor/yiisoft/session/src/SessionMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#21 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(104): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#22 /app/vendor/yiisoft/error-handler/src/Middleware/ErrorCatcher.php(135): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#23 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(104): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#24 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#25 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(50): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#26 /app/vendor/yiisoft/yii-http/src/Application.php(87): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#27 /app/vendor/yiisoft/yii-runner-http/src/HttpApplicationRunner.php(103): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#28 /app/public/index.php(36): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#29 {main}
```

**Comment by albertborsos** [comment]
I had some time to dig deeper into it.

As @vjik said it is a problem, because it will try to call `getCreated_at` method.
If I replace it with
```php
$methodName = 'get' . (new Inflector())->toPascalCase($field);
```
, then it will be OK, but it is still magic. 

The next issue is with the following line:
https://github.com/yiisoft/data/blob/55fd80895765cae9e125489d2c119b150ac4e596/src/Paginator/KeysetPaginator.php#L262 
If the `getValueFromItem` returns a `\DateTimeInterface` then it is not possible to cast it to string.

https://github.com/yiisoft/data/blob/55fd80895765cae9e125489d2c119b150ac4e596/src/Paginator/KeysetPaginator.php#L309

I made a new method:
```php
    /**
     * @param mixed $item
     *
     * @return mixed
     */
    private function getStringValueFromItem($item, string $field): string
    {
        $value = $this->getValueFromItem($item, $field);
        if ($value instanceof \DateTimeImmutable) {
            return (string) $value->getTimestamp();
        }

        return (string) $value;
    }
```
And I replaced these two lines:
https://github.com/yiisoft/data/blob/55fd80895765cae9e125489d2c119b150ac4e596/src/Paginator/KeysetPaginator.php#L262
https://github.com/yiisoft/data/blob/55fd80895765cae9e125489d2c119b150ac4e596/src/Paginator/KeysetPaginator.php#L268
to:
```php
$this->currentFirstValue = $this->getStringValueFromItem($item, $field);
```
and
```php
$this->currentLastValue = $this->getStringValueFromItem($item, $field);
```

After these modifications it sorts well for datetime fields too.
Of course there may be more values that cannot be casted to string.

**Comment by albertborsos** [comment]
Is there any reason the `KeysetPaginator` class is `final`?
I like in Yii 2.0 that I can easily override the classes of the framework and I can use it if I configure it in the config files.

Now I would like to extend the `KeysetPaginator` class and fix it with my own methods while it is not fixed in this repository.
But it is not possible since this class is `final`.

**Comment by albertborsos** [comment]
I realised that `KeysetPaginator` is not good for my scenario (I just picked it from the demo app).

Because if I want to order by date, there could be multiple records with the same date, and `KeysetPaginator` will not know by the token which was the last record with the same date.

So I found `OffsetPaginator` which works great for my scenario.

**Comment by samdark** [comment]
@albertborsos would you please submit pull requests with your changes? Preferably separate ones but one PR would do as well.

Classes are final by default in Yii3. There are many advantages and disadvantages in this decision but that's how it is.
